# Generated by Django 3.2.3 on 2021-07-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20210622_1358'),
        ('trains', '0002_traintest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_set', to='cities.city', verbose_name='Город отправления'),
        ),
    ]
