# Generated by Django 4.0.4 on 2022-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_auto_20210703_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
